name: Test

on: [push]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - elixir: 1.14.5
            erlang: 25.3.0
    steps:
      - uses: actions/checkout@v3
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-mix
      - name: Install dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Run Tests
        run: mix test
      - name: Run formatter
        run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
